export enum LinePatternName {
	Arc1 = "Arc1",
	Arc2 = "Arc2",
	DashedDotted = "DashedDotted",
	Dashed = "Dashed",
	Ditch = "Ditch",
	Dotted = "Dotted",
	DoubleDashed = "DoubleDashed",
	DoubleEmptyTriangle = "DoubleEmptyTriangle",
	EmptyRectangle = "EmptyRectangle",
	Double = "Double",
	EmptyTriangle = "EmptyTriangle",
	SharpTriangle = "SharpTriangle",
	SmallRectangle = "SmallRectangle",
	SmallTriangle1 = "SmallTriangle1",
	SmallTriangle2 = "SmallTriangle2",
	Solid = "Solid",
	Triangle1 = "Triangle1",
	Triangle2 = "Triangle2",
	TwoSidesRectangle = "TwoSidesRectangle",
	X = "X"
}